In [2]:
import os
import pandas as pd
import numpy as np

from IPython import get_ipython


from sklearn.metrics import mean_absolute_error as mae

import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')

import seaborn as sns
sns.set()

import plotly
import plotly.express as px
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.io as pio
init_notebook_mode(connected=True)

In [145]:
path = './data/time_series_covid19_confirmed_global.csv'
df = pd.read_csv(path)
df.head(10)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20
0,NaN,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,7,11,16,21,22,22,22,24,24,40
1,NaN,Albania,41.1533,20.1683,0,0,0,0,0,0,...,33,38,42,51,55,59,64,70,76,89
2,NaN,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,26,37,48,54,60,74,87,90,139,201
3,NaN,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,1,1,1,2,39,39,53,75,88,113
4,NaN,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,2,2
5,NaN,Antigua and Barbuda,17.0608,-61.7964,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
6,NaN,Argentina,-38.4161,-63.6167,0,0,0,0,0,0,...,31,34,45,56,68,79,97,128,158,266
7,NaN,Armenia,40.0691,45.0382,0,0,0,0,0,0,...,8,18,26,52,78,84,115,136,160,194
8,Australian Capital Territory,Australia,-35.4735,149.0124,0,0,0,0,0,0,...,1,1,1,2,2,3,4,6,9,19
9,New South Wales,Australia,-33.8688,151.2093,0,0,0,0,3,4,...,92,112,134,171,210,267,307,353,436,669

In [146]:
df['country_region'] = df['Country/Region'] + '_' + df['Province/State'].map(lambda x: str(x))
df.head(20)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20,country_region
0,NaN,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,11,16,21,22,22,22,24,24,40,Afghanistan_nan
1,NaN,Albania,41.1533,20.1683,0,0,0,0,0,0,...,38,42,51,55,59,64,70,76,89,Albania_nan
2,NaN,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,37,48,54,60,74,87,90,139,201,Algeria_nan
3,NaN,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,1,1,2,39,39,53,75,88,113,Andorra_nan
4,NaN,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,0,0,0,0,0,0,1,2,2,Angola_nan
5,NaN,Antigua and Barbuda,17.0608,-61.7964,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,Antigua and Barbuda_nan
6,NaN,Argentina,-38.4161,-63.6167,0,0,0,0,0,0,...,34,45,56,68,79,97,128,158,266,Argentina_nan
7,NaN,Armenia,40.0691,45.0382,0,0,0,0,0,0,...,18,26,52,78,84,115,136,160,194,Armenia_nan
8,Australian Capital Territory,Australia,-35.4735,149.0124,0,0,0,0,0,0,...,1,1,2,2,3,4,6,9,19,Australia_Australian Capital Territory
9,New South Wales,Australia,-33.8688,151.2093,0,0,0,0,3,4,...,112,134,171,210,267,307,353,436,669,Australia_New South Wales
10,Northern Territory,Australia,-12.4634,130.8456,0,0,0,0,0,0,...,1,1,1,1,1,1,3,3,5,Australia_Northern Territory
11,Queensland,Australia,-28.0167,153.4000,0,0,0,0,0,0,...,46,61,68,78,94,144,184,221,259,Australia_Queensland
12,South Australia,Australia,-34.9285,138.6007,0,0,0,0,0,0,...,19,20,29,29,37,42,50,67,100,Australia_South Australia
13,Tasmania,Australia,-41.4545,145.9707,0,0,0,0,0,0,...,5,6,7,7,10,10,10,16,22,Australia_Tasmania
14,Victoria,Australia,-37.8136,144.9631,0,0,0,0,1,1,...,49,57,71,94,121,121,121,229,355,Australia_Victoria
15,Western Australia,Australia,-31.9505,115.8605,0,0,0,0,0,0,...,17,17,28,31,35,52,64,90,120,Australia_Western Australia
16,NaN,Austria,47.5162,14.5501,0,0,0,0,0,0,...,655,860,1018,1332,1646,2013,2388,2814,3582,Austria_nan
17,NaN,Azerbaijan,40.1431,47.5769,0,0,0,0,0,0,...,15,23,28,28,28,44,44,53,65,Azerbaijan_nan
18,NaN,Bahamas,25.0343,-77.3963,0,0,0,0,0,0,...,0,0,1,1,1,3,3,4,4,Bahamas_nan
19,NaN,Bahrain,26.0275,50.5500,0,0,0,0,0,0,...,210,214,214,228,256,278,285,305,334,Bahrain_nan

In [147]:
df.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20', '1/28/20', '1/29/20',
       '1/30/20', '1/31/20', '2/1/20', '2/2/20', '2/3/20', '2/4/20', '2/5/20',
       '2/6/20', '2/7/20', '2/8/20', '2/9/20', '2/10/20', '2/11/20', '2/12/20',
       '2/13/20', '2/14/20', '2/15/20', '2/16/20', '2/17/20', '2/18/20',
       '2/19/20', '2/20/20', '2/21/20', '2/22/20', '2/23/20', '2/24/20',
       '2/25/20', '2/26/20', '2/27/20', '2/28/20', '2/29/20', '3/1/20',
       '3/2/20', '3/3/20', '3/4/20', '3/5/20', '3/6/20', '3/7/20', '3/8/20',
       '3/9/20', '3/10/20', '3/11/20', '3/12/20', '3/13/20', '3/14/20',
       '3/15/20', '3/16/20', '3/17/20', '3/18/20', '3/19/20', '3/20/20',
       '3/21/20', '3/22/20', 'country_region'],
      dtype='object')

In [148]:
result_path = './data/time_series_20200323.csv'
result_df = pd.read_csv(result_path)
result_df.head(10)

Empty DataFrame
Columns: [date, country, region, lat, long, confirmed, deaths]
Index: []

In [149]:
dates = ['1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20', '1/28/20', '1/29/20',
       '1/30/20', '1/31/20', '2/1/20', '2/2/20', '2/3/20', '2/4/20', '2/5/20',
       '2/6/20', '2/7/20', '2/8/20', '2/9/20', '2/10/20', '2/11/20', '2/12/20',
       '2/13/20', '2/14/20', '2/15/20', '2/16/20', '2/17/20', '2/18/20',
       '2/19/20', '2/20/20', '2/21/20', '2/22/20', '2/23/20', '2/24/20',
       '2/25/20', '2/26/20', '2/27/20', '2/28/20', '2/29/20', '3/1/20',
       '3/2/20', '3/3/20', '3/4/20', '3/5/20', '3/6/20', '3/7/20', '3/8/20',
       '3/9/20', '3/10/20', '3/11/20', '3/12/20', '3/13/20', '3/14/20',
       '3/15/20', '3/16/20', '3/17/20', '3/18/20', '3/19/20', '3/20/20',
       '3/21/20', '3/22/20']

In [150]:
result_columns = result_df.columns

In [151]:

for index, row in df.iterrows():
    for date in dates:
        isert_row = [date, row['Country/Region'], row['Province/State'], row['Lat'], row['Long'], row[date], 0]        
        new_df = pd.DataFrame([isert_row], columns=result_columns)
        print(new_df)
        result_df = result_df.append(new_df)

  0
     date     country  region        lat       long  confirmed  deaths
0  3/3/20  Mozambique     NaN -18.665695  35.529562          0       0
     date     country  region        lat       long  confirmed  deaths
0  3/4/20  Mozambique     NaN -18.665695  35.529562          0       0
     date     country  region        lat       long  confirmed  deaths
0  3/5/20  Mozambique     NaN -18.665695  35.529562          0       0
     date     country  region        lat       long  confirmed  deaths
0  3/6/20  Mozambique     NaN -18.665695  35.529562          0       0
     date     country  region        lat       long  confirmed  deaths
0  3/7/20  Mozambique     NaN -18.665695  35.529562          0       0
     date     country  region        lat       long  confirmed  deaths
0  3/8/20  Mozambique     NaN -18.665695  35.529562          0       0
     date     country  region        lat       long  confirmed  deaths
0  3/9/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/10/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/11/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/12/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/13/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/14/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/15/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/16/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/17/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/18/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/19/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/20/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/21/20  Mozambique     NaN -18.665695  35.529562          0       0
      date     country  region        lat       long  confirmed  deaths
0  3/22/20  Mozambique     NaN -18.665695  35.529562          1       0
      date country  region        lat       long  confirmed  deaths
0  1/22/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  1/23/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  1/24/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  1/25/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  1/26/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  1/27/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  1/28/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  1/29/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  1/30/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  1/31/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  2/1/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  2/2/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  2/3/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  2/4/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  2/5/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  2/6/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  2/7/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  2/8/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  2/9/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/10/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/11/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/12/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/13/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/14/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/15/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/16/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/17/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/18/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/19/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/20/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/21/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/22/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/23/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/24/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/25/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/26/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/27/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/28/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  2/29/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  3/1/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  3/2/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  3/3/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  3/4/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  3/5/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  3/6/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  3/7/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  3/8/20   Syria     NaN  34.802075  38.996815          0       0
     date country  region        lat       long  confirmed  deaths
0  3/9/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/10/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/11/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/12/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/13/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/14/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/15/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/16/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/17/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/18/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/19/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/20/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/21/20   Syria     NaN  34.802075  38.996815          0       0
      date country  region        lat       long  confirmed  deaths
0  3/22/20   Syria     NaN  34.802075  38.996815          1       0
      date      country  region       lat        long  confirmed  deaths
0  1/22/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  1/23/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  1/24/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  1/25/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  1/26/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  1/27/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  1/28/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  1/29/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  1/30/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  1/31/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  2/1/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  2/2/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  2/3/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  2/4/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  2/5/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  2/6/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  2/7/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  2/8/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  2/9/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/10/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/11/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/12/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/13/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/14/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/15/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/16/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/17/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/18/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/19/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/20/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/21/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/22/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/23/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/24/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/25/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/26/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/27/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/28/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  2/29/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  3/1/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  3/2/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  3/3/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  3/4/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  3/5/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  3/6/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  3/7/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  3/8/20  Timor-Leste     NaN -8.874217  125.727539          0       0
     date      country  region       lat        long  confirmed  deaths
0  3/9/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/10/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/11/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/12/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/13/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/14/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/15/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/16/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/17/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/18/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/19/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/20/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/21/20  Timor-Leste     NaN -8.874217  125.727539          0       0
      date      country  region       lat        long  confirmed  deaths
0  3/22/20  Timor-Leste     NaN -8.874217  125.727539          1       0

In [152]:
result_df.head(20)

      date      country region   lat  long confirmed deaths
0  1/22/20  Afghanistan    NaN  33.0  65.0         0      0
0  1/23/20  Afghanistan    NaN  33.0  65.0         0      0
0  1/24/20  Afghanistan    NaN  33.0  65.0         0      0
0  1/25/20  Afghanistan    NaN  33.0  65.0         0      0
0  1/26/20  Afghanistan    NaN  33.0  65.0         0      0
0  1/27/20  Afghanistan    NaN  33.0  65.0         0      0
0  1/28/20  Afghanistan    NaN  33.0  65.0         0      0
0  1/29/20  Afghanistan    NaN  33.0  65.0         0      0
0  1/30/20  Afghanistan    NaN  33.0  65.0         0      0
0  1/31/20  Afghanistan    NaN  33.0  65.0         0      0
0   2/1/20  Afghanistan    NaN  33.0  65.0         0      0
0   2/2/20  Afghanistan    NaN  33.0  65.0         0      0
0   2/3/20  Afghanistan    NaN  33.0  65.0         0      0
0   2/4/20  Afghanistan    NaN  33.0  65.0         0      0
0   2/5/20  Afghanistan    NaN  33.0  65.0         0      0
0   2/6/20  Afghanistan    NaN  33.0  65.0         0      0
0   2/7/20  Afghanistan    NaN  33.0  65.0         0      0
0   2/8/20  Afghanistan    NaN  33.0  65.0         0      0
0   2/9/20  Afghanistan    NaN  33.0  65.0         0      0
0  2/10/20  Afghanistan    NaN  33.0  65.0         0      0

In [153]:
result_df.size

101199

In [155]:
result_df.to_csv('./data/time_series_20200323.csv', index = False)